replicaCount: 1
revisionHistoryLimit: 5
namespace: core
showSBLogs: true
image:
  repository: http-sender-amqp
  tag: latest
  pullPolicy: IfNotPresent
ports: 80
configs:
  AZURE_SERVICEBUS_AUTOLOCKRENEWAL_SECONDS: 900
  AZURE_SERVICEBUS_MAXCONCURRENTCALLS: 1
  ASYNC_ACTION: asyncactions
secrets:
  AZURE_SERVICEBUS_CONNECTION_STRING: "TO BE REPLACE"

  