apiVersion: v1
kind: Service
metadata:
  name: http-sender-amqp
  namespace: {{ .Values.namespace }}
spec:
  selector:
    name: http-sender-amqp
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.ports }}
{{- if .Values.debugMode}}
      nodePort: 32222
  type: NodePort
  {{- end }}