apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: http-sender-amqp-secret
  namespace: {{ .Values.namespace }}
data:
  AZURE_SERVICEBUS_CONNECTION_STRING: "{{ .Values.secrets.AZURE_SERVICEBUS_CONNECTION_STRING | b64enc }}"
  